### ISSUE TITLE
Download doesn't work in 1.5.0

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/LightDMS#1]
CallStack:
2019-01-14 10:13:16.1112|ERROR|DownloadHelper|System.ArgumentNullException: Value cannot be null.
Parameter name: transactionContext
   at System.Data.SqlTypes.SqlFileStream..ctor(String path, Byte[] transactionContext, FileAccess access, FileOptions options, Int64 allocationSize)
   at Rhetos.LightDMS.DownloadHelper.TryDownloadFromFileStream(HttpContext context, FileMetadata file, SqlConnection sqlConnection) in C:\My Projects\RhetosPackages\LightDMS\Plugins\Rhetos.LightDMS\Download\DownloadHelper.cs:line 196
   at Rhetos.LightDMS.DownloadHelper.HandleDownload(HttpContext context, Nullable`1 documentVersionId, Nullable`1 fileContentId) in C:\My Projects\RhetosPackages\LightDMS\Plugins\Rhetos.LightDMS\Download\DownloadHelper.cs:line 42

When tried to do DownloadPreview.
SqlServer: 2017 Developer edition

Detected that query:
SELECT 
    fc.Content.PathName(),
    GET_FILESTREAM_TRANSACTION_CONTEXT()
FROM 
    LightDMS.FileContent fc

returns null in context column when transaction is not started.

Downgrade to 1.3.0 fixes the problem.

**Comment by bantolov** [comment]
Thank you for the bug report.
It is critical issue, and the patch will be released in the next few days.
